apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-data-volume-1
spec:
  storageClassName: cloud-aws-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-aws-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---

